# Generated by Django 4.2.4 on 2023-08-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.tag'),
        ),
    ]
