# Generated by Django 4.2.4 on 2023-08-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_tag',
        ),
    ]
