# Generated by Django 4.2.4 on 2023-08-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_prioridad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prioridad',
            new_name='Priority',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='tipo_prioridad',
            new_name='priority_type',
        ),
    ]
