# Generated by Django 4.2.4 on 2023-08-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority_type',
            field=models.CharField(max_length=6),
        ),
    ]
